name: json_god
version: 2.0.0
authors:
  - Tobe O <thosakwe@gmail.com>
description: Easy JSON serialization and deserialization in Dart.
homepage: https://github.com/thosakwe/json_god
environment:
  sdk: ">=1.8.0 <3.0.0"
dependencies:
  dart2_constant: ^1.0.0
  logging: ^0.11.0
dev_dependencies:
  stack_trace: ^1.0.0
  test: ^1.0.0
